name: Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Read file
        id: set-matrix
        run: |
          matrixStringifiedObject="$(jq -c . .github/elixir-test-matrix.json)"
          echo "matrix=$matrixStringifiedObject" >> $GITHUB_OUTPUT
  format:
    needs: test-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26.2.1'
          elixir-version: '1.12.3'
          version-type: strict
      - run: mix format --check-formatted
      - run: mix format --check-formatted "monitors/**/*.ex"
      - run: mix format --check-formatted "examples/**/*.ex"

  test:
    needs: test-matrix
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp_version}} / Elixir ${{matrix.elixir_version}}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_version}}
          elixir-version: ${{matrix.elixir_version}}
          rebar3-version: ${{ matrix.rebar3_version }}
          version-type: strict
      - run: mix deps.get
        name: Deps
      - run: mix test
      - run: mix dialyzer

  test-examples:
    needs: test-matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/org_uplink
    name: Examples - OTP ${{matrix.otp_version}} / Elixir ${{matrix.elixir_version}}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_version}}
          elixir-version: ${{matrix.elixir_version}}
          rebar3-version: ${{ matrix.rebar3_version }}
      - run: mix deps.get
      - run: mix test
